apiVersion: v1
kind: Service
metadata:
  name: {{app_name}}-service
  labels:
    app: {{app_name}}
spec:
  selector:
    app: {{app_name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{app_name}}-deployment
  labels:
    app: {{app_name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{app_name}}
  template:
    metadata:
      labels:
        app: {{app_name}}
    spec:
      restartPolicy: Always
      containers:
      - name: {{app_name}}
        image: {{aws_account_id}}.dkr.ecr.ap-northeast-1.amazonaws.com/{{app_name}}:TAG
        envFrom:
          - configMapRef:
              name: {{app_name}}-config
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
